### PR TITLE
Add an additional learning resources section

### PR DESCRIPTION
**Pull request by jgarte**
Hi,

This pull request adds a new learning resources section and links in a first crash course on Textual.

### CODE REVIEW

**Comment by davep** [comment]
Thanks. Do you happen to know if the author will be updating this resource as Textual evolves? (I ask because there's one very old third party tutorial out there that is massively out of date and seems to keep tripping people up; I wouldn't want this document to point to other tutorials that might suffer the same fate)

**Comment by jgarte** [comment]
Hi,

I asked the author in the reply feed of the article.

**Comment by davep** [comment]
Awesome. Thanks.

**Comment by josevnz** [comment]
And author says it is not a problem (I love talking about myself in third person :smile: )

**Comment by jgarte** [comment]
The questioner says thanks! (me too 😄 )

**Comment by davep** [comment]
Thanks all, so I take it the intention is to keep updating the document, yeah?

**Comment by josevnz** [comment]
Yes indeed. Now to keep it up to date I can do on GitHub for sure, not sure what is the policy with Fedora Magazine (I'll ask).

**Pull request merged**
